#!/bin/sh

MINENAME="cicermine"
DBNAME="cicermine-dev"

## add triggers
./gradlew generateUpdateTriggers
psql -f dbmodel/build/resources/main/add-update-triggers.sql $DBNAME

## do updates
cd ~/java/ncgr/intermine

echo "########## cdsreferenceupdater $MINENAME"
./cdsreferenceupdater $MINENAME

echo "########## transcriptreferenceupdater $MINENAME"
./transcriptreferenceupdater $MINENAME

echo "########## blowing away secondaryIdentifier $MINENAME"
psql -c "UPDATE bioentity SET secondaryidentifier = null" $DBNAME

echo "########## update genefamily.size $DBNAME ##########"
psql $DBNAME -c "UPDATE genefamily SET intermine_size = (SELECT count(*) FROM gene WHERE gene.genefamilyid=genefamily.id)"

## remove triggers
cd ~/$MINENAME
psql -f dbmodel/build/resources/main/remove-update-triggers.sql $DBNAME
