#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "########################## ${LP}EXPRESSION${NC} ###########################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm3.ann1.expr.CDC_Consul.Perilla-Henao_2018
./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm3.ann1.expr.Hybrid.Cook_2018
./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm3.ann1.expr.mixed.Moenga_2018
./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018a
./gradlew integrate --stacktrace -Psource=CDCFrontier.gnm3.ann1.expr.mixed.Sutton_2018b
