#!/bin/sh
NC='\033[0m'
LP='\033[1;35m'

echo -e "#################################################################"
echo -e "########################## ${LP}DESCRIPTIONS${NC} #########################"
echo -e "#################################################################"

./gradlew integrate --stacktrace -Psource=Cicer-arietinum-description
./gradlew integrate --stacktrace -Psource=Cicer-echinospermum-description
./gradlew integrate --stacktrace -Psource=Cicer-reticulatum-description
./gradlew integrate --stacktrace -Psource=Medicago-truncatula-description
./gradlew integrate --stacktrace -Psource=Trifolium-pratense-description
./gradlew integrate --stacktrace -Psource=Lotus-japonicus-description
