#!/bin/sh

echo ""
echo "#######################################################################################"
echo "#######################################################################################"
echo "################################### POSTPROCESS #######################################"
echo "#######################################################################################"
echo "#######################################################################################"
echo ""

## IM CORE
# ./gradlew postprocess -Pprocess=do-sources
# ./gradlew postprocess -Pprocess=create-utr-references
# ./gradlew postprocess -Pprocess=create-references
# ./gradlew postprocess -Pprocess=make-spanning-locations
# ./gradlew postprocess -Pprocess=create-chromosome-locations-and-lengths
# ./gradlew postprocess -Pprocess=create-intergenic-region-features
# ./gradlew postprocess -Pprocess=transfer-sequences
# ./gradlew postprocess -Pprocess=populate-child-features
# ./gradlew postprocess -Pprocess=create-gene-flanking-features

## LIS
# ./gradlew postprocess -Pprocess=lis-populate-gene-protein-collections
# ./gradlew postprocess -Pprocess=lis-populate-publications

## VIEWS AND INDEXES
# ./gradlew postprocess -Pprocess=create-location-overlap-index
## ## this is not used ## ./gradlew postprocess -Pprocess=create-overlap-view

## DO THESE AFTER ALL UPDATES
./gradlew postprocess -Pprocess=create-attribute-indexes
./gradlew postprocess -Pprocess=summarise-objectstore
./gradlew postprocess -Pprocess=create-autocomplete-index
./gradlew postprocess -Pprocess=create-search-index
